export type Vacancy = {
  id: number;
  title: string;
  companyName: string;
  location: string;
  tags: string[];
  date: string;
  jobType: string;
  schedule: string;
  experience: number;
  salary: {
    from: number;
    to: number;
  };
};
export const VACANCIES: Vacancy[] = [
  {
    id: 1,
    title: "Front-end intern1",
    companyName: "internet lux",
    location: "Москва",
    date: "29/03/2021",
    schedule: "Полный день",
    jobType: "Частичная занятость",
    experience: 1,
    tags: [
      "jQuery",
      "JavaScript",
      "CSS3",
      "React",
      "Git",
      "Vue",
      "Flexbox",
      "HTML5",
    ],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 2,
    title: "Front-end intern2",
    companyName: "internet lux",
    location: "Москва",
    date: "29/03/2021",
    jobType: "Частичная занятость",
    schedule: "Гибкий график",
    experience: 2,
    tags: [
      "jQuery",
      "JavaScript",
      "CSS3",
      "React",
      "Git",
      "Vue",
      "Flexbox",
      "HTML5",
    ],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 3,
    experience: 3,
    title: "Front-end intern3",
    companyName: "internet lux",
    location: "Москва",
    date: "29/03/2021",
    jobType: "Проектная работа",
    schedule: "Удаленная работа",
    tags: [
      "jQuery",
      "JavaScript",
      "CSS3",
      "React",
      "Git",
      "Vue",
      "Flexbox",
      "HTML5",
    ],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 4,
    experience: 4,
    title: "Front-end intern4",
    companyName: "internet lux4",
    location: "Москва",
    date: "29/03/2021",
    jobType: "Стажировка",
    schedule: "Полный день",
    tags: ["Git", "Vue", "Flexbox", "HTML5"],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 5,
    title: "Front-end intern5",
    companyName: "internet lux5",
    location: "Москва",
    experience: 5,
    date: "29/03/2021",
    jobType: "Стажировка",
    schedule: "Полный день",
    tags: ["jQuery", "JavaScript", "CSS3", "React"],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 6,
    title: "Front-end Developer",
    companyName: "Tech Innovations",
    location: "Москва",
    date: "29/03/2021",
    schedule: "Полный день",
    jobType: "Частичная занятость",
    experience: 1,
    tags: ["jQuery", "JavaScript", "CSS3", "React", "Git"],
    salary: { from: 15000, to: 300000 },
  },
  {
    id: 7,
    title: "Back-end Developer",
    companyName: "Creative Labs",
    location: "Санкт-Петербург",
    date: "15/05/2022",
    schedule: "Гибкий график",
    jobType: "Полная занятость",
    experience: 3,
    tags: ["Node.js", "Express", "MongoDB", "Python"],
    salary: { from: 60000, to: 150000 },
  },
  {
    id: 8,
    title: "UI/UX Designer",
    companyName: "Design Studio",
    location: "Казань",
    date: "01/01/2023",
    schedule: "Удаленная работа",
    jobType: "Стажировка",
    experience: 0,
    tags: ["Figma", "Photoshop", "Sketch"],
    salary: { from: 20000, to: 50000 },
  },
  {
    id: 9,
    title: "Full Stack Developer",
    companyName: "Global Tech",
    location: "Екатеринбург",
    date: "20/11/2021",
    schedule: "Полный день",
    jobType: "Частичная занятость",
    experience: 2,
    tags: ["React", "Node.js", "SQL"],
    salary: { from: 80000, to: 180000 },
  },
  {
    id: 10,
    title: "Data Analyst",
    companyName: "Data Solutions",
    location: "Нижний Новгород",
    date: "12/08/2022",
    schedule: "Гибкий график",
    jobType: "Проектная работа",
    experience: 4,
    tags: ["Python", "SQL", "Data Visualization"],
    salary: { from: 90000, to: 200000 },
  },
  {
    id: 11,
    title: "DevOps Engineer",
    companyName: "Cloud Systems",
    location: "Ростов-на-Дону",
    date: "05/03/2023",
    schedule: "Удаленная работа",
    jobType: "Полная занятость",
    experience: 5,
    tags: ["AWS", "Docker", "Kubernetes"],
    salary: { from: 100000, to: 250000 },
  },
  {
    id: 12,
    title: "Mobile App Developer",
    companyName: "App Development",
    location: "Уфа",
    date: "10/09/2021",
    schedule: "Полный день",
    jobType: "Частичная занятость",
    experience: 2,
    tags: ["Flutter", "Dart", "iOS"],
    salary: { from: 70000, to: 160000 },
  },
  {
    id: 13,
    title: "Product Manager",
    companyName: "Tech Innovations",
    location: "Волгоград",
    date: "23/02/2022",
    schedule: "Гибкий график",
    jobType: "Полная занятость",
    experience: 6,
    tags: ["Agile", "Scrum", "Market Research"],
    salary: { from: 120000, to: 300000 },
  },
  {
    id: 14,
    title: "SEO Specialist",
    companyName: "Web Marketing",
    location: "Челябинск",
    date: "30/06/2023",
    schedule: "Удаленная работа",
    jobType: "Стажировка",
    experience: 0,
    tags: ["SEO", "Google Analytics", "Content Marketing"],
    salary: { from: 15000, to: 40000 },
  },
  {
    id: 15,
    title: "Network Administrator",
    companyName: "IT Solutions",
    location: "Тюмень",
    date: "18/07/2022",
    schedule: "Полный день",
    jobType: "Проектная работа",
    experience: 3,
    tags: ["Cisco", "Networking", "Security"],
    salary: { from: 50000, to: 120000 },
  },
  {
    id: 16,
    title: "Graphic Designer",
    companyName: "Creative Agency",
    location: "Набережные Челны",
    date: "14/04/2023",
    schedule: "Гибкий график",
    jobType: "Частичная занятость",
    experience: 2,
    tags: ["Adobe Illustrator", "Photoshop"],
    salary: { from: 30000, to: 70000 },
  },
  {
    id: 17,
    title: "Cloud Architect",
    companyName: "Cloud Technologies",
    location: "Саратов",
    date: "22/10/2021",
    schedule: "Удаленная работа",
    jobType: "Полная занятость",
    experience: 5,
    tags: ["AWS", "Azure", "GCP"],
    salary: { from: 110000, to: 250000 },
  },
  {
    id: 18,
    title: "Content Writer",
    companyName: "Content Creators",
    location: "Воронеж",
    date: "17/05/2022",
    schedule: "Гибкий график",
    jobType: "Частичная занятость",
    experience: 1,
    tags: ["Blogging", "SEO", "Copywriting"],
    salary: { from: 25000, to: 60000 },
  },
  {
    id: 19,
    title: "Game Developer",
    companyName: "Gaming Studio",
    location: "Калуга",
    date: "29/11/2023",
    schedule: "Полный день",
    jobType: "Проектная работа",
    experience: 4,
    tags: ["Unity", "C#", "Game Design"],
    salary: { from: 80000, to: 200000 },
  },
  {
    id: 20,
    title: "Cybersecurity Analyst",
    companyName: "Security Solutions",
    location: "Ижевск",
    date: "09/08/2022",
    schedule: "Удаленная работа",
    jobType: "Полная занятость",
    experience: 3,
    tags: ["Ethical Hacking", "Network Security"],
    salary: { from: 60000, to: 140000 },
  },
];
